server:
  port: 80
spring:
  application:
    name: mycat-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8066/TESTDB
    username: root
    password: root
